import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://yrjlmqxpakjiwrfwhgaj.supabase.co';
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyamxxeHBhY2ppd3Jmd2hnYWoiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQ4Mzg2MzgzLjEwMSwiZXhwIjoxOTYzOTYyMzgzfQ.dCXvC6xCvWChDSxG4H7Qj4R2vBj5XQGdNvzHnG7Cq9Q';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const tablesSQL = `
-- Tabla usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  telefono TEXT,
  area TEXT,
  rol TEXT DEFAULT 'Usuario',
  direccion TEXT,
  password TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla acciones_correctivas
CREATE TABLE IF NOT EXISTS acciones_correctivas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT,
  fecha_deteccion DATE,
  proceso TEXT,
  area TEXT,
  origen TEXT,
  num_auditoria TEXT,
  indicador_ref TEXT,
  descripcion_nc TEXT,
  posibles_causas TEXT,
  causa_raiz TEXT,
  clasificacion TEXT,
  tipo_accion TEXT,
  accion_contencion TEXT,
  evidencia_contencion TEXT,
  eficacia TEXT,
  actividades JSONB,
  estado TEXT DEFAULT 'BORRADOR',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla planes_mejora
CREATE TABLE IF NOT EXISTS planes_mejora (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT,
  fecha_elaboracion DATE,
  area TEXT,
  proceso TEXT,
  situacion_actual TEXT,
  situacion_deseada TEXT,
  beneficios TEXT,
  equipo_trabajo TEXT,
  origen_mejora TEXT,
  just_beneficios TEXT,
  impacto_esperado TEXT,
  recursos_necesarios TEXT,
  presupuesto TEXT,
  actividades JSONB,
  estado TEXT DEFAULT 'BORRADOR',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla indicadores_data
CREATE TABLE IF NOT EXISTS indicadores_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicador_id BIGINT,
  area TEXT,
  mes TEXT,
  anio TEXT,
  valor NUMERIC,
  observaciones TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla riesgos
CREATE TABLE IF NOT EXISTS riesgos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  riesgo TEXT,
  causa TEXT,
  efecto TEXT,
  probabilidad INTEGER DEFAULT 2,
  impacto INTEGER DEFAULT 2,
  control TEXT,
  tipo TEXT DEFAULT 'Riesgo',
  area TEXT,
  direccion TEXT,
  proceso TEXT,
  plan_accion TEXT,
  fecha_termino DATE,
  evaluacion TEXT,
  estado_plan TEXT DEFAULT 'SIN_PLAN',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla documentos
CREATE TABLE IF NOT EXISTS documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT,
  tipo TEXT,
  area TEXT,
  version TEXT,
  estado TEXT,
  fecha DATE,
  autor TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla auditorias
CREATE TABLE IF NOT EXISTS auditorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero TEXT,
  tipo TEXT,
  area TEXT,
  fecha_inicio DATE,
  fecha_fin DATE,
  estado TEXT,
  hallazgos INTEGER,
  no_conformidades INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla evidencias
CREATE TABLE IF NOT EXISTS evidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT,
  tipo TEXT,
  data TEXT,
  fecha DATE,
  documento TEXT,
  documento_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
`;

async function createTables() {
  console.log('Creating tables in Supabase...');
  
  try {
    // Create tables using raw SQL
    const { data, error } = await supabase.rpc('exec_sql', { sql: tablesSQL });
    
    if (error) {
      console.log('RPC method not available, trying alternative...');
    }
    
    console.log('Tables creation attempted');
    return { success: true };
  } catch (e) {
    console.error('Error:', e);
    return { error: e.message };
  }
}

createTables()
  .then(result => console.log('Result:', result))
  .catch(console.error);