export { default as IndicadoresView } from './IndicadoresView';
export { default as DesempenoProcesosTab } from './DesempenoProcesosTab';
export { default as FichasGubernamentalesTab } from './FichasGubernamentalesTab';
export { default as ProyectosPresupuestoTab } from './ProyectosPresupuestoTab';
export { default as ControlPresupuestalAreasTab } from './ControlPresupuestalAreasTab';
export { default as EvaluacionTrimestralTab } from './EvaluacionTrimestralTab';
export { default as ModalFichaTecnicaAyuntamiento } from './ModalFichaTecnicaAyuntamiento';
export { default as ModalGestionarIndicador } from './ModalGestionarIndicador';
export { default as ModalGestionProyectoPresupuestario } from './ModalGestionProyectoPresupuestario';
export { default as ModalGenerarRC } from './ModalGenerarRC';
export { default as ModalGestionarRC } from './ModalGestionarRC';
export { default as ModalRecordatorioAtrasos } from './ModalRecordatorioAtrasos';
export { default } from './IndicadoresView';