-- Tablas para SGC Portal - OOMAPASC

-- Tabla: usuarios
create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text unique not null,
  telefono text,
  area text,
  rol text default 'Usuario',
  direccion text,
  password text,
  created_at timestamp with time zone default now()
);

-- Tabla: acciones_correctivas
create table if not exists acciones_correctivas (
  id bigint generated by default as identity primary key,
  codigo text,
  estado text default 'BORRADOR',
  area text,
  proceso text,
  origen text,
  numero_auditoria text,
  descripcion_no_conformidad_original text,
  descripcion_no_conformidad_ia text,
  descripcion_no_conformidad_final text,
  impacta_otros_procesos text default 'NO',
  otros_procesos_afectados text,
  accion_contenedora text,
  actividad_inmediata text,
  responsable_actividad_inmediata text,
  fecha_actividad_inmediata date,
  herramienta_analisis text,
  requiere_actualizar_matriz_riesgos text default 'NO',
  descripcion_riesgo_oportunidad text,
  requiere_cambio_sgc text default 'NO',
  fecha_creacion_borrador timestamp with time zone,
  fecha_generacion_ia timestamp with time zone,
  fecha_envio_sgc timestamp with time zone,
  fecha_aprobacion_sgc timestamp with time zone,
  fecha_apertura timestamp with time zone,
  fecha_cierre timestamp with time zone,
  usuario_solicitante text,
  aprobado_por_sgc text,
  auditor_cierre text,
  resultado_cierre text,
  evidencia_objetiva_revisada text,
  conclusion_eficacia text,
  clave_formato text default 'OOMRSC-20',
  revision_formato text default 'Rev. 18',
  equipo_json jsonb,
  causas_json jsonb,
  actividades_json jsonb,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- Tabla: planes_mejora
create table if not exists planes_mejora (
  id bigint generated by default as identity primary key,
  codigo text not null,
  fecha_elaboracion date,
  proceso text,
  area text,
  situacion_actual text,
  situacion_deseada text,
  beneficios text,
  equipo_trabajo text,
  origen_mejora text,
  just_beneficios text,
  impacto_esperado text,
  recursos_necesarios text,
  presupuesto text,
  actividades jsonb,
  estado text default 'BORRADOR',
  created_at timestamp with time zone default now()
);

-- Tabla: indicadores_data
create table if not exists indicadores_data (
  id bigint generated by default as identity primary key,
  indicador_id bigint,
  area text,
  mes text,
  anio text,
  valor numeric,
  observaciones text,
  created_at timestamp with time zone default now()
);

-- Tabla: riesgos
create table if not exists riesgos (
  id bigint generated by default as identity primary key,
  riesgo text not null,
  causa text,
  efecto text,
  probabilidad integer default 2,
  impacto integer default 2,
  control text,
  tipo text default 'Riesgo',
  area text,
  direccion text,
  proceso text,
  plan_accion text,
  fecha_termino date,
  evaluacion text,
  estado_plan text default 'SIN_PLAN',
  created_at timestamp with time zone default now()
);

-- Tabla: documentos
create table if not exists documentos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  tipo text,
  area text,
  version text,
  estado text,
  fecha date,
  autor text,
  created_at timestamp with time zone default now()
);

-- Tabla: auditorias
create table if not exists auditorias (
  id bigint generated by default as identity primary key,
  numero text not null,
  tipo text,
  area text,
  fecha_inicio date,
  fecha_fin date,
  estado text,
  hallazgos integer,
  no_conformidades integer,
  created_at timestamp with time zone default now()
);

-- Habilitar RLS
alter table usuarios enable row level security;
alter table acciones_correctivas enable row level security;
alter table planes_mejora enable row level security;
alter table indicadores_data enable row level security;
alter table riesgos enable row level security;
alter table documentos enable row level security;
alter table auditorias enable row level security;

-- Políticas públicas (para desarrollo)
create policy "Allow all usuarios" on usuarios for all using (true);
create policy "Allow all acciones_correctivas" on acciones_correctivas for all using (true);
create policy "Allow all planes_mejora" on planes_mejora for all using (true);
create policy "Allow all indicadores_data" on indicadores_data for all using (true);
create policy "Allow all riesgos" on riesgos for all using (true);
create policy "Allow all documentos" on documentos for all using (true);
create policy "Allow all auditorias" on auditorias for all using (true);

-- Tabla: informes_auditoria
create table if not exists informes_auditoria (
  id bigint generated by default as identity primary key,
  anio integer not null,
  numero integer not null,
  nombre text not null,
  tipo text default 'PDF',
  url text,
  created_at timestamp with time zone default now()
);

alter table informes_auditoria enable row level security;
create policy "Allow all informes_auditoria" on informes_auditoria for all using (true);